// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("sagan")>]
[<assembly: AssemblyProductAttribute("sagan")>]
[<assembly: AssemblyDescriptionAttribute("F# client for Cosmos DB")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "sagan"
    let [<Literal>] AssemblyProduct = "sagan"
    let [<Literal>] AssemblyDescription = "F# client for Cosmos DB"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
